# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 08:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=64)),
                ('ip', models.GenericIPAddressField()),
            ],
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.IntegerField(choices=[(0, '\u666e\u901a\u7528\u6237'), (1, '\u9ad8\u7ea7\u7528\u6237')])),
                ('name', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=32)),
                ('address', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
                ('user_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='studentsapp.UserInfo')),
            ],
        ),
        migrations.AddField(
            model_name='usergroup',
            name='user_info',
            field=models.ManyToManyField(to='studentsapp.UserInfo'),
        ),
        migrations.AddField(
            model_name='host',
            name='user_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentsapp.UserGroup'),
        ),
    ]
