# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-06 09:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentsapp', '0002_auto_20161208_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadfile',
            name='aa',
        ),
        migrations.RemoveField(
            model_name='uploadfile',
            name='fds',
        ),
    ]
