# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-06 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_auto_20161209_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userblog',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userblog',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='userblog',
            name='pwd',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
