# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-09 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.FileField(null=True, upload_to=b'blogapp/static/img/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='habby',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sex',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='favorite_animal',
            field=models.EmailField(max_length=254),
        ),
    ]
