# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-19 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20161209_0929'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '\u7c7b\u522b\u76ee\u5f55', 'verbose_name_plural': '\u7c7b\u522b\u76ee\u5f55'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': '\u79cd\u7c7b', 'verbose_name_plural': '\u79cd\u7c7b'},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='price',
            field=models.FloatField(blank=True, help_text=b'there is a price', null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=128, verbose_name=b'\xe7\xb1\xbb\xe5\x88\xab'),
        ),
    ]
