# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-20 08:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20161219_0800'),
    ]

    operations = [
        migrations.RunSQL('alter table accounts_category convert to charset gbk;', reverse_sql=None)
    ]
