# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-20 08:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_tablename_encode2'),
    ]

    operations = [
        migrations.RunSQL("alter table accounts_category character set utf8;", reverse_sql=None)
    ]
