# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-06 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20161220_0846'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=3)),
                ('symbol', models.CharField(max_length=3)),
                ('rate', models.FloatField(help_text=b'here is the rate base on dollar')),
                ('display', models.CharField(max_length=3)),
            ],
            options={
                'verbose_name_plural': 'Currencies',
            },
        ),
    ]
